"""Resource limits and observability constants (Slice 7)."""

from __future__ import annotations

from wetlabdb.sar.repository import MAX_SNAPSHOT_COMPOUNDS

MAX_ALIGNMENT_COMPOUNDS = MAX_SNAPSHOT_COMPOUNDS
LIVE_ALIGN_MAX_COMPOUNDS = 15
MAX_OPTIMIZER_TIME_SECONDS = 30.0
MAX_ENUMERATED_SOLUTIONS_DEFAULT = 10_000
BENCHMARK_COMPOUND_COUNTS = (5, 15, 30)
ALIGNMENT_RUN_TIMEOUT_SECONDS = 120.0

__all__ = [
    "ALIGNMENT_RUN_TIMEOUT_SECONDS",
    "BENCHMARK_COMPOUND_COUNTS",
    "LIVE_ALIGN_MAX_COMPOUNDS",
    "MAX_ALIGNMENT_COMPOUNDS",
    "MAX_ENUMERATED_SOLUTIONS_DEFAULT",
    "MAX_OPTIMIZER_TIME_SECONDS",
]
